iojs:
  image: iojs:latest
  script:
  - node -v
  - npm --unsafe-perm --proxy http://gotfix.com:7777/ --https-proxy http://gotfix.com:7777/ --strict-ssl false install
  - npm test

node11:
  image: node:0.11
  script:
  - node -v
  - npm --unsafe-perm --proxy http://gotfix.com:7777/ --https-proxy http://gotfix.com:7777/ --strict-ssl false install
  - npm test
  
node12:
  image: node:0.12
  script:
  - node -v
  - npm --unsafe-perm --proxy http://gotfix.com:7777/ --https-proxy http://gotfix.com:7777/ --strict-ssl false install
  - npm test