iojs:
  image: iojs:latest
  script:
  - node -v
  - pwd
  - ls -l /
  - npm --unsafe-perm install
  - npm test

node11:
  image: node:0.11
  script:
  - node -v
  - npm --unsafe-perm install
  - npm test
  
node12:
  image: node:0.12
  script:
  - node -v
  - npm --unsafe-perm install
  - npm test