image: iojs:latest
image: node:0.11
image: node:0.12

before_script:
  - npm install

Bleeding Edge:
  script:
  - npm test

Stable Release:
  script:
  - npm test
  tags:
  - release
  only:
  - tags