iojs:
  image: iojs:latest
  script:
  - npm install
  - npm test

node11:
  image: node:0.11
  script:
  - npm install
  - npm test
  
node12:
  image: node:0.12
  script:
  - npm install
  - npm test