before_script:
  - add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - apt-get update -qq
  - apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - npm install

Bleeding Edge:
  script:
  - npm test

Stable Release:
  script:
  - npm test
  tags:
  - cross
  only:
  - tags