iojs:
  image: iojs:latest
  script:
  - node -v
  - npm --unsafe-perm --registry=http://npm.gotfix.com install
  - npm test

node11:
  image: node:0.11
  script:
  - node -v
  - npm --unsafe-perm --registry=http://npm.gotfix.com install
  - npm test
  
node12:
  image: node:0.12
  script:
  - node -v
  - npm --unsafe-perm --registry=http://npm.gotfix.com install
  - npm test